version: '2.1'

services:
  kafkahq-ui:
    image: tchiotludo/kafkahq
    environment:
      KAFKAHQ_CONFIGURATION: |
        kafkahq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: kafka-broker-1:19092
                security.protocol: SASL_PLAINTEXT
                sasl.mechanism: PLAIN
                sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka_user_informer" password="kafka-pwd-informer";
    ports:
      - 8992:8080